# Generated by Django 4.2.3 on 2023-07-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
