# Generated by Django 4.2.3 on 2023-07-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_events_alter_tournament_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
