# Generated by Django 4.2.3 on 2023-07-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0006_alter_events_end_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Events",
            new_name="Event",
        ),
    ]
