# Generated by Django 4.2.3 on 2023-07-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0007_rename_events_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
