# Generated by Django 4.2.3 on 2023-07-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_announcments_announcements"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Announcements",
            new_name="Announcement",
        ),
    ]
