# Generated by Django 4.2.3 on 2023-07-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_announcements_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="home")),
                ("description", models.TextField(max_length=500)),
                ("hyperlink", models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name="Announcement",
        ),
    ]
