# Generated by Django 4.2.3 on 2023-07-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_photo_delete_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="home")),
                ("description", models.TextField(max_length=1000)),
                ("button_name", models.TextField(max_length=50)),
                ("button_hyperlink", models.URLField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="photo",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
