# Generated by Django 4.2.3 on 2023-07-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_announcement_alter_photo_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="photo",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
