# Generated by Django 4.2.3 on 2023-07-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_photo_description_alter_photo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="button_hyperlink",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="button_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
