# Generated by Django 4.2.3 on 2023-08-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_announcement_button_hyperlink_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="button_hyperlink",
            field=models.URLField(
                blank=True,
                help_text="Note: this field is REQUIRED if button name is not empty.",
            ),
        ),
    ]
