# Generated by Django 4.2.3 on 2023-08-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_announcement_button_hyperlink_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="hyperlink",
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Note: this field is REQUIRED if button name is not empty.",
            ),
        ),
    ]
