# Generated by Django 4.2.3 on 2023-08-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_remove_photo_hyperlink_alter_announcement_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="button_hyperlink",
            field=models.URLField(
                blank=True,
                help_text="Note: this field is REQUIRED if button name is not empty.",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
