# Generated by Django 4.2.3 on 2023-08-08 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_announcement_button_hyperlink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="hyperlink",
        ),
    ]
