# Generated by Django 4.2.3 on 2023-07-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "team",
                    models.CharField(
                        choices=[(1, "Illini 1s"), (2, "Illini 2s"), (3, "Illini 3s")],
                        max_length=9,
                    ),
                ),
                ("position", models.CharField(max_length=50)),
                ("major", models.CharField(max_length=50)),
            ],
        ),
    ]
