# Generated by Django 4.2.3 on 2023-07-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="player",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
