# Generated by Django 4.2.3 on 2023-07-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0002_rename_name_player_first_name_player_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.CharField(
                choices=[
                    ("Illini 1s", "Illini 1s"),
                    ("Illini 1s", "Illini 2s"),
                    ("Illini 1s", "Illini 3s"),
                ],
                max_length=9,
            ),
        ),
    ]
