# Generated by Django 4.2.3 on 2023-07-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0003_alter_player_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
