# Generated by Django 4.2.3 on 2023-07-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0004_player_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="height",
            field=models.CharField(
                default="", help_text="Enter in format [feet]'[inches]\"", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="number",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
