# Generated by Django 4.2.3 on 2023-07-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0005_player_height_player_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="major",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
