# Generated by Django 4.2.3 on 2023-07-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0008_alter_player_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="image",
            field=models.ImageField(default="profile_icon.png", upload_to="roster"),
        ),
    ]
